version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./schema/:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '9080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress custom
  webserver:
    depends_on:
      - db
    build: .
    ports:
      - '9000:80'
    restart: always
    volumes: ['./html/:/var/www/html']
    environment:
      WORDPRESS_DB_NAME: local
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: